/*
 * Algod REST API.
 *
 * API endpoint for algod operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct InlineResponse2008 {
    /// encoding of the participation ID.
    #[serde(rename = "partId")]
    pub part_id: String,
}

impl InlineResponse2008 {
    pub fn new(part_id: String) -> InlineResponse2008 {
        InlineResponse2008 {
            part_id,
        }
    }
}


